name: Test Pull Requests

on:
  pull_request:
    branches:
      - main
      - feat/cicd-pr-run

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build  .
  run:
    name: Python Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Telegram Bot
        timeout-minutes: 3
        run: python main.py
